desktop section revamp
cryptomator/docs pull request #39
Opened 2023-05-05 15:52 UTC by ready-to-pwn

Mostly rephrased the desktop section to be technically accurate. Take a look and let me know if there are any discrepancies.

2023-05-08 15:42 UTC, tobihagemann requested changes

2023-05-08 15:42 UTC, tobihagemann commented on source/desktop/password-and-recovery-key.rst
> +You can access it by selecting a vault, lock it if necessary and click on ``Vault Options``.
```suggestion
You can access it by selecting a vault, lock it if necessary, and click on ``Vault Options``.
```

2023-05-08 15:42 UTC, tobihagemann commented on source/desktop/password-and-recovery-key.rst
> +Navigate to the ``Vault options`` -> ``Password`` tab, and click on ``Change Password``.
```suggestion
Navigate to the ``Vault Options`` -> ``Password`` tab, and click on ``Change Password``.
```

2023-05-08 15:42 UTC, tobihagemann commented on source/desktop/password-and-recovery-key.rst
> +A new window will open displaying a sequence of words (i.e. the recovery key).
```suggestion
A new window will open displaying a sequence of words (i.e., the recovery key).
```

2023-05-08 15:42 UTC, tobihagemann commented on source/desktop/password-and-recovery-key.rst
> +    By design, *any* valid recovery key is accepted, but that does not mean *any* valid recovery key can reset the vault's password correctly. **A valid but incorrect key will make your old data inac
```suggestion
    By design, *only* the correct recovery key is accepted. **A valid but incorrect key won't be accepted to prevent your old data from becoming inaccessible.**
```

This was improved in https://github.com/cryptomator/cryptomator/pull/2686.

2023-05-08 15:42 UTC, tobihagemann commented on source/desktop/setup.rst
> +Download and installation process varies depending on your operating system, follow the instructions for your operating system.
```suggestion
Download and installation process varies depending on your operating system. Follow the instructions for your operating system.
```

2023-05-08 15:42 UTC, tobihagemann commented on source/desktop/setup.rst
> +We have included *FUSE-T for macOS* with the ``.dmg`` installer, so you don't need to install it seperately.
1. We haven't killed off FUSE for macOS yet (I just noticed, it's actually called macFUSE now). It's still recommended for Intel Macs. We recommend FUSE-T for Apple Silicon.
2. The dmg installer doesn't include FUSE drivers. It's indeed a separate download. The dmg installer contains a _link_ to macFUSE or FUSE-T, depending on the architecture.
3. I wouldn't say that a FUSE driver _needs_ to be installed because Cryptomator works with WebDAV without third-party drivers. There is a "catch" though on Apple Silicon Macs because WebDAV is buggy so it's definitely recommended.

I know, it's quite a mess at the moment. Hopefully, we can integrate FUSE-T into Cryptomator soon and take it out of the experimental stage.

2023-05-08 15:42 UTC, tobihagemann commented on source/desktop/vault-management.rst
> +For your operating system or other apps a vault is a just a normal directory containing some encrypted files.
```suggestion
For your operating system or other apps, a vault is a just a normal directory containing some encrypted files.
```

2023-05-08 15:42 UTC, tobihagemann commented on source/desktop/vault-management.rst
> +Only Cryptomator understands can decrypt the vault's contents when you unlock it using a password.
```suggestion
Only Cryptomator can decrypt the vault's contents when you unlock it using a password.
```

2023-05-08 15:42 UTC, tobihagemann commented on source/desktop/vault-management.rst
> +    The vault's is **not** deleted from your PC by removing it from the list. You need to delete the vault directory to permentantly delete your encrypted files using the file manager.
```suggestion
    The vault is **not** deleted from your PC by removing it from the list. If you wish to permanently delete your encrypted files, you need to delete the vault directory using the file manager.
```

2023-05-08 15:42 UTC, tobihagemann commented on source/desktop/vault-management.rst
> +Each vault has it's own settings which can be customized under vault options.
```suggestion
Each vault has its own settings which can be customized under vault options.
```

2023-05-08 15:42 UTC, tobihagemann commented on source/desktop/vault-management.rst
> +To open a vault's settings, select a vault, lock it, and click on ``Vault Options`` (gear icon).
```suggestion
To open a vault's settings, select a vault, lock it, and click on ``Vault Options``.
```

Maybe we shouldn't mention the gear icon for "vault options" since we use a similar icon for the preferences.

2023-05-08 15:42 UTC, tobihagemann commented on source/desktop/vault-management.rst
> +1. General - Options not fitting in other categories
```suggestion
1. General - Options not fitting in other categories.
```

2023-05-08 15:42 UTC, tobihagemann commented on source/desktop/volume-type.rst
> +When a vault is unlocked it is integrated (also called mounted) into the operating system as a virtual drive, so you can browse the decrypted files.
```suggestion
When a vault is unlocked, it is integrated (also called mounted) into the operating system as a virtual drive, so you can browse the decrypted files.
```

2023-05-08 15:42 UTC, tobihagemann commented on source/desktop/volume-type.rst
> +The availabe volume types depend on your operating system and if required libraries are installed (e.g., macFUSE-T).
```suggestion
The availabe volume types depend on your operating system and if required libraries are installed (e.g., FUSE-T).
```

2023-05-08 15:42 UTC, tobihagemann commented on source/desktop/volume-type.rst
> +WebDAV on utlizes the scripting language `AppleScript` to handle WebDAV operations.
```suggestion
WebDAV on macOS utlizes the scripting language `AppleScript` to mount/unmount the virtual drive.
```

2023-05-10 13:53 UTC, infeo commented on source/desktop/accessing-vaults.rst
> +Once unlocked, the vault's contents will be shown via an attached virtual drive on your PC.
Maybe add in a sentence, that alternatively the vault can also be shown in a directory (and link to volume type section)

2023-05-10 13:58 UTC, infeo commented on source/desktop/accessing-vaults.rst
> +Click on ``Reveal Drive`` in the Cryptomator window to open the virtual drive using the default file manager (Windows Explorer, Finder, ...).
Also, i think it is good to mention here, that albeit the user sees his decrypted files, they are not stored unencrypted. Something like:
> Even though your files are shown unencrypted in the virtual drive, they are not stored unencrypted on the hard drive but only in [volatile memory](https://en.wikipedia.org/wiki/Volatile_memory)

2023-05-10 14:02 UTC, infeo commented on source/desktop/volume-type.rst
> +Default Volume Type
This section is not about the "Default" volume type, but about general information about volume types

2023-05-10 14:10 UTC, infeo commented on source/desktop/volume-type.rst
> +WebDAV Volume Type
i suggest to use plural: "WebDAV Volume Types"

2023-05-10 14:10 UTC, infeo commented on source/desktop/volume-type.rst
> +FUSE Volume Type
i suggest to use plural: "FUSE Volume Types"

2023-05-10 14:14 UTC, infeo commented on source/desktop/volume-type.rst
> +    FUSE-T is a new project, so you may come across bugs here and there.
"here and there" is a quite... lightweight formulation. Since users entrust Cryptomator with their data, i suggest to be more serious.

2023-05-10 14:18 UTC, infeo commented on source/desktop/volume-type.rst
> +FUSE with WinFsp depends on a library provided by the `WinFsp project <https://winfsp.dev/>`_.
```diff
+ This volume type binds to a library provided by the `WinFsp project <https://winfsp.dev/>`_.
-  The `WinFsp project <https://winfsp.dev/>`_ provides FUSE bindings for Windows.
```

2023-05-10 14:19 UTC, infeo commented on source/desktop/volume-type.rst
> +    Dokany support in Cryptomator is deprecated since version 1.7.0. We suggest a to switch to :ref:`desktop/volume-type/fuse/winfsp`.
```diff
-     Dokany support in Cryptomator is deprecated since version 1.7.0. We suggest a to switch to :ref:`desktop/volume-type/fuse/winfsp`.
+     Dokany support in Cryptomator is deprecated since version 1.7.0. We suggest to switch to :ref:`desktop/volume-type/fuse/winfsp`.

2023-05-15 11:07 UTC, overheadhunter commented on source/desktop/volume-type.rst
> +WebDAV Volume Type
I plead to remove this subsection altogether.

Instead of 

```txt
├─ volume types
│  ├─ general
│  ├─ fuse
│  │  ├─ fuse (linux)
│  │  ├─ fuse-t (mac)
│  │  ├─ macfuse (mac)
│  │  ├─ winfsp (win)
│  ├─ webdav
│  │  ├─ webdav (windows)
│  │  ├─ webdav (gio)
│  │  ├─ webdav (apple script)
│  │  ├─ webdav (http address)
```

I would rather see:

```txt
├─ general
├─ volume types
│  ├─ fuse (linux)
│  ├─ fuse-t (mac)
│  ├─ macfuse (mac)
│  ├─ winfsp (win)
│  ├─ webdav (windows)
│  ├─ webdav (gio)
│  ├─ webdav (apple script)
│  ├─ webdav (http address)
```

2023-05-15 11:07 UTC, overheadhunter commented on source/desktop/volume-type.rst
> +FUSE Volume Type
(see https://github.com/cryptomator/docs/pull/39#discussion_r1193682340)

2023-05-15 13:56 UTC, overheadhunter commented on source/desktop/volume-type.rst
> +WebDAV Volume Type
> What's the problem with current structure?

The documentation should reflect the structure in the software. And the software doesn't have such a sub-hierarchy. All implementations are 100% exchangeable. From a user's perspective it doesn't matter what kind of protocol is used internally. This would be like grouping applications by the programming language used, while the user really just wants to know whether the application is a game or a text editor.

I don't see any benefit in explaining what FUSE and WebDAV is _in general_. Instead we should focus on what are the pros and cons of each _individual implementation_ are.

2023-05-16 14:40 UTC, overheadhunter commented on source/desktop/volume-type.rst
> +WebDAV Volume Type
In that case, how about putting the "general" info about FUSE and WebDAV into the "general" section as well? It is just one sentence each, anyway.

2023-05-18 10:44 UTC, overheadhunter commented on source/desktop/volume-type.rst
> +WebDAV Volume Type
Sure, go ahead 🙂

2023-06-01 18:35 UTC, ghost commented
Ready to push!

2023-06-06 14:58 UTC, tobihagemann requested changes
I was wondering about the "volume type" headings. You're suggesting the following:

- FUSE (Linux)
- FUSE-T (macOS)
- macFUSE (macOS)
- WinFsp / WinFsp (Windows Local Drive)
- WebDAV (Windows Explorer)
- WebDAV (Linux)
- WebDAV (macOS)
- WebDAV (HTTP Address - All OS)
- Dokany (Windows)

The naming isn't consistent and I'm also wondering about the order of things. From a user's perspective, I'm probably interested in information for _my_ operating system. And for recognizability, we should use the actual display names of the providers and also use the order based on the priority.

My suggestion would be the following:

- Windows
  - WinFsp / WinFsp (Local Drive)
  - WebDAV (Windows Explorer)
  - Dokany (1.5)
- macOS
  - macFUSE
  - FUSE-T (Experimental)
  - WebDAV (AppleScript)
- Linux
  - FUSE
  - WebDAV (gio)
- Common
  - WebDAV (HTTP Address)

2023-06-06 14:58 UTC, tobihagemann commented on source/desktop/setup.rst
> +Install *macFUSE* if your MacBook comes with an Intel CPU or install *FUSE-T* if your MacBook comes with an Apple Silicon CPU.
```suggestion
On macOS, Cryptomator will use WebDAV volume type by default if no FUSE driver is installed on the system. But we recommend installing *macFUSE* or *FUSE-T* for a smoother file browsing experience.
Install *macFUSE* if your Mac comes with an Intel CPU or install *FUSE-T* if your Mac comes with an Apple Silicon CPU.
```

2023-06-06 14:58 UTC, tobihagemann commented on source/desktop/volume-type.rst
> +This mounting of a virtual drive is handled differently depending on the volume type chosen in Cryptomator's settings.
```suggestion
This mounting of a virtual drive is handled differently depending on the volume type chosen in Cryptomator's preferences.
```

2023-06-06 14:58 UTC, tobihagemann commented on source/desktop/volume-type.rst
> +The availability of volume types depends on your operating system and installed libraries.
```suggestion
The availability of volume types depends on your operating system and installed drivers.
```

2023-06-07 12:06 UTC, ghost commented
> I was wondering about the "volume type" headings. You're suggesting the following:
> 
>     * FUSE (Linux)
> 
>     * FUSE-T (macOS)
> 
>     * macFUSE (macOS)
> 
>     * WinFsp / WinFsp (Windows Local Drive)
> 
>     * WebDAV (Windows Explorer)
> 
>     * WebDAV (Linux)
> 
>     * WebDAV (macOS)
> 
>     * WebDAV (HTTP Address - All OS)
> 
>     * Dokany (Windows)
> 
> 
> The naming isn't consistent and I'm also wondering about the order of things. From a user's perspective, I'm probably interested in information for _my_ operating system. And for recognizability, we should use the actual display names of the providers and also use the order based on the priority.
> 
> My suggestion would be the following:
> 
>     * Windows
>       
>       * WinFsp / WinFsp (Local Drive)
>       * WebDAV (Windows Explorer)
>       * Dokany (1.5)
> 
>     * macOS
>       
>       * macFUSE
>       * FUSE-T (Experimental)
>       * WebDAV (AppleScript)
> 
>     * Linux
>       
>       * FUSE
>       * WebDAV (gio)
> 
>     * Common
>       
>       * WebDAV (HTTP Address)

@tobihagemann Well, it wasn't my suggestion, but it looked good to me. 

Anyway, the new structure looks better in my opinion. Because:
>  From a user's perspective, I'm probably interested in information for my operating system.

Thanks, I will make the edits :)

2023-06-12 11:22 UTC, ghost commented
@tobihagemann Ready to push!

2023-06-12 13:11 UTC, merged