updated Linux FUSE requirements
cryptomator/docs pull request #42
Opened 2023-08-21 07:52 UTC by gordon-shumway-net

in my experience on Debian 11 it was not enough to have just the libfuse3 Library installed, the fuse3 Package was needed as well to mount a Cryptomator Vault with FUSE, otherwise I got Java Errors on the CLI.

2023-08-21 07:52 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/cryptomator/docs?pullRequest=42) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/cryptomator/docs?pullRequest=42) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/cryptomator/docs?pullRequest=42) it.</sub>

2023-08-21 08:34 UTC, infeo requested changes
Thank you for the contribution!

2023-08-21 08:34 UTC, infeo commented on source/desktop/volume-type.rst
> +**Requirements:** Linux, ``libfuse3`` and/or ``fuse3`` installed
Remove the libfuse3 package completely. Cryptomator needs `fusermount3`, which is only shipped with the fuse3 package.

2023-08-27 15:32 UTC, overheadhunter requested changes
Maybe this assumption can be expressed a bit more vague.

2023-08-27 15:32 UTC, overheadhunter commented on source/desktop/volume-type.rst
> +Luckily, `fuse3` comes pre-installed on all major Linux distributions.
Our issue tracker suggests the package is missing quite often 😉

2023-08-28 12:46 UTC, infeo approved these changes

2023-08-28 12:47 UTC, merged