Desktop privacy section
cryptomator/docs pull request #48
Opened 2023-10-25 10:05 UTC by mindmonk

A privacy section has been introduced in the Desktop documentation, elucidating data processing during error handling.

2023-10-25 10:21 UTC, SailReal requested changes
Just some minor hints...

Is it also planned to add a sentence about the "Look up solution" button?

2023-10-25 10:21 UTC, SailReal commented on source/desktop/privacy.rst
> +
```suggestion
```

2023-10-25 10:21 UTC, SailReal commented on source/desktop/privacy.rst
> +Without your explicit consent, no requests will be executed, as this feature operates solely on an Opt-In basis.
```suggestion
Without your explicit consent, no requests will be executed, as this feature operates solely on an opt-in basis.
```

2023-10-26 15:22 UTC, tobihagemann commented
I have a much broader question. Are we sure that we want to add a privacy section in the docs? Shouldn't it be part of the privacy policy under section 8 on our website? https://cryptomator.org/privacy/#app

2023-11-13 10:04 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/cryptomator/docs?pullRequest=48) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/cryptomator/docs?pullRequest=48) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/cryptomator/docs?pullRequest=48) it.</sub>

2023-11-27 17:46 UTC, mindmonk commented
I agree with your comment. Accordingly, I am closing the pull request.

2023-11-27 17:46 UTC, closed without merging